update BrocObject key
Change-Id: I907161133093b3b6af8b66d040a43f30b3e3c942

diff --git a/tools/install b/tools/install
--- a/tools/install
+++ b/tools/install
@@ -10,6 +10,7 @@ help()
     echo "     deploy : deploy borc "
     echo '     protobuf : install protobuf in $HOME'
     echo '     proto : compile proto files'
+    echo '     broc: compile proto files'
 }
 
 deploy_protobuf()
@@ -37,12 +38,20 @@ deploy_proto()
     echo "-- compile broc proto files ..."
     $PROTOC -I=../proto --python_out=../dependency ../proto/*.proto
     if [ $? -ne 0 ]; then
-        echo "-- compile broc proto files failed"
-        return 1
-    else
-        echo "-- compile broc proto files success"
-        return 0
-    fi
+    [ $? -ne 0 ] && echo "-- compile broc proto files failed" && return 1
+    echo "-- compile broc proto files success" && return 0
+}
+
+deploy_broc()
+{
+    mkdir -p /opt/broc
+    [ $? -ne 0 ] && echo "-- fail to mkdir /opt/broc" && return 1
+    cp -rf ../* /opt/broc
+    [ $? -ne 0 ] && echo "-- install broc failed" && return 1
+    grep 'PATH=/opt/broc/bin' ~/.bash_profile
+    if [ $? -ne 0 ]:
+        echo 'PATH=/opt/broc/client:$PATH'  >> ~/.bash_profile
+    echo "-- install broc OK, and run: source ~/.bash_profile" && return 0
 }
 
 deploy()
@@ -50,6 +59,8 @@ deploy()
     deploy_protobuf
     [ $? -ne 0 ] && return 1
     deploy_proto
+    [ $? -ne 0 ] && return 1
+    deploy_broc
     [ $? -ne 0 ] && return 1
     return 0
 }
@@ -64,6 +75,9 @@ case "$1" in
         proto)
                 deploy_proto
                 ;;     
+        broc)
+                deploy_broc
+                ;;
              *)
                 help
                 ;;
